name: CI
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: build-image
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - device: generic-amd64
          - device: generic-arm64

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{secrets.CI_TOKEN}}
          submodules: true

      - name: prepare vendor
        run: go mod tidy && go mod vendor

      - name: build-system-image
        run: go run rlxos.dev/tools/ignite -device ${{matrix.device}} -cache-path ${{secrets.CACHE_PATH}}
